project:
  type: website
execute:
  freeze: auto
website:
  title: "La reprise d'emploi est-elle rémunératrice?"
  page-navigation: true
  site-url: "https://gallegre.github.io/GainEemploi/"
  repo-url: "https://github.com/gallegre/GainEmploi"
  reader-mode: false
  bread-crumbs: true
  favicon: www/fofce.png
  page-footer:
      border: true
      left: "![](/www/ccby4.png){height='16'}"
      right: "propulsé par ![](/www/quarto.png){height='16'}"
  navbar:
    title: false
    search: true
    code-tools: true
    bakground: "#FEFEFE"
    logo: www/ofce_m.png
    logo-alt: "OFCE"
    logo-href: "https://www.ofce.fr/"
    right:
      - text: " "
        icon: person-circle
        href: about.html
      - text: " "
        icon: github
        href: https://gallegre.github.io/GainEemploi/

comments:
  hypothesis: true
format:
  ofce-html: default

